/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.OrderController;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Products;

/**
 *
 * @author markj
 */
public class CashierView extends javax.swing.JFrame {

    /**
     * Creates new form CashierView
     */
    public CashierView() {
        initComponents();
        setLocationRelativeTo(null);
        
        removeButtonTransparency();
        
    }
     private void removeButtonTransparency(){ // removed: btn opacity and btn increment and decrement highlighting effects when pressed.
        JButton[] btns = {btnSearch};
        for(JButton btn : btns){
            btn.setContentAreaFilled(false);
        }
    }
    private OrderController controller = new OrderController();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnOrderingViewExit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtOrderID = new javax.swing.JTextArea();
        btnSearch = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMyOrder = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtTAX = new javax.swing.JTextField();
        jtxtSubtotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        setResizable(false);

        jPanel1.setBackground(java.awt.Color.white);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/profileicon.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 145, 147));

        btnOrderingViewExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Elegantthemes-Beautiful-Flat-Power.48.png"))); // NOI18N
        btnOrderingViewExit.setBorderPainted(false);
        btnOrderingViewExit.setContentAreaFilled(false);
        btnOrderingViewExit.setFocusPainted(false);
        btnOrderingViewExit.setFocusable(false);
        btnOrderingViewExit.setRequestFocusEnabled(false);
        btnOrderingViewExit.setRolloverEnabled(false);
        btnOrderingViewExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderingViewExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnOrderingViewExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("00-00-0000");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 230, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Hi, Cashier001!");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 230, 30));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(179, 215, 197));
        jPanel6.setPreferredSize(new java.awt.Dimension(510, 0));

        jtxtOrderID.setColumns(1);
        jtxtOrderID.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jtxtOrderID.setRows(1);
        jtxtOrderID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 102)));
        jScrollPane1.setViewportView(jtxtOrderID);

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/search.png"))); // NOI18N
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        btnSearch.setFocusPainted(false);
        btnSearch.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/search-pressed.png"))); // NOI18N
        btnSearch.setRequestFocusEnabled(false);
        btnSearch.setRolloverEnabled(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/cancel.png"))); // NOI18N
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        btnCancel.setFocusPainted(false);
        btnCancel.setRequestFocusEnabled(false);
        btnCancel.setRolloverEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnPay.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/money.png"))); // NOI18N
        btnPay.setBorderPainted(false);
        btnPay.setContentAreaFilled(false);
        btnPay.setFocusPainted(false);
        btnPay.setRequestFocusEnabled(false);
        btnPay.setRolloverEnabled(false);
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Receipt Total");

        jtxtTotal.setBackground(java.awt.Color.white);
        jtxtTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtTotal.setForeground(java.awt.Color.black);
        jtxtTotal.setToolTipText("");
        jtxtTotal.setBorder(null);
        jtxtTotal.setOpaque(true);
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("__________________________________________________");

        jTableMyOrder.setBackground(new java.awt.Color(179, 215, 197));
        jTableMyOrder.setForeground(java.awt.Color.black);
        jTableMyOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Qty", "Product", "Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableMyOrder.setEnabled(false);
        jTableMyOrder.setFocusable(false);
        jTableMyOrder.setShowGrid(false);
        jTableMyOrder.getTableHeader().setResizingAllowed(false);
        jTableMyOrder.getTableHeader().setReorderingAllowed(false);
        jTableMyOrder.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTableMyOrderInputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jTableMyOrder);

        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("TAX");

        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Subtotal");

        jtxtTAX.setEditable(false);
        jtxtTAX.setBackground(new java.awt.Color(255, 255, 255));
        jtxtTAX.setForeground(new java.awt.Color(0, 0, 0));
        jtxtTAX.setBorder(null);
        jtxtTAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTAXActionPerformed(evt);
            }
        });

        jtxtSubtotal.setEditable(false);
        jtxtSubtotal.setBackground(new java.awt.Color(255, 255, 255));
        jtxtSubtotal.setForeground(java.awt.Color.black);
        jtxtSubtotal.setToolTipText("");
        jtxtSubtotal.setBorder(null);
        jtxtSubtotal.setOpaque(true);
        jtxtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubtotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtTAX, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSearch)
                        .addComponent(btnPay))
                    .addComponent(btnCancel))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPay)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel5)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel4))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jtxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jtxtTAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnCancel))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       
       
        try {
            int customerId = Integer.parseInt(jtxtOrderID.getText());
            List<Products> orderedProducts = controller.getOrdersByCustomerId(customerId);

            DefaultTableModel model = (DefaultTableModel) jTableMyOrder.getModel();
            model.setRowCount(0); // clears previous data

            for (Products p : orderedProducts) {
                Object[] row = {p.getQuantity() ,p.getName(), p.getPrice(), p.getTotalPrice()};
                model.addRow(row);
            }
            double total = controller.calculateTotal();
            double subtotal = controller.calculateSubtotal();
            double tax = controller.calculateTax();
            jtxtTotal.setText(String.format("%.2f", total));
            jtxtSubtotal.setText(String.format("%.2f", subtotal));
            jtxtTAX.setText(String.format("%.2f", tax));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Customer ID");
        }
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jTableMyOrderInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTableMyOrderInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMyOrderInputMethodTextChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            int customerId = Integer.parseInt(jtxtOrderID.getText());       
            boolean statusUpdated = controller.updateOrderStatus(customerId, "Canceled"); //update status to 'Canceled'

            if (statusUpdated) {
                
                boolean deleted = controller.deleteCanceledOrders(customerId); //delete canceled orders

                if (deleted) {
                    JOptionPane.showMessageDialog(null, "Order Canceled and Deleted.");
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to delete canceled orders.");
                }            
                btnSearchActionPerformed(null); // Refresh table data after deletion
        } else {
            JOptionPane.showMessageDialog(null, "Failed to cancel order.");
        }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Customer ID");
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        try {
            int customerId = Integer.parseInt(jtxtOrderID.getText());
            boolean success = controller.updateOrderStatus(customerId, "Paid");

            if (success) {
                JOptionPane.showMessageDialog(null, "Order marked as Paid.");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to update order status.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Customer ID");
        }
        //jTableMyOrder.setVisible(false); // tempo to disappear table
        //jScrollPane2.setVisible(false);
    }//GEN-LAST:event_btnPayActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed

    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtTAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTAXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTAXActionPerformed

    private void jtxtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubtotalActionPerformed

    }//GEN-LAST:event_jtxtSubtotalActionPerformed

    private void btnOrderingViewExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderingViewExitActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Do you want to exit?", "Ordering View", JOptionPane.YES_NO_OPTION);

        if(result == JOptionPane.YES_OPTION){
            new MainMenu().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnOrderingViewExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierView().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOrderingViewExit;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMyOrder;
    private javax.swing.JTextArea jtxtOrderID;
    private javax.swing.JTextField jtxtSubtotal;
    private javax.swing.JTextField jtxtTAX;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
