/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author markj
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setLocationRelativeTo(null);
        
        removeButtonTransparency();
    }
    private void removeButtonTransparency(){ // removed: btn opacity and btn increment and decrement highlighting effects when pressed.
        JButton[] btns = {buttonManager1, buttonCashier, buttonCustomer};
        for(JButton btn : btns){
            btn.setContentAreaFilled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonCashier = new javax.swing.JButton();
        buttonManager1 = new javax.swing.JButton();
        buttonCustomer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1089, 631));
        setMinimumSize(new java.awt.Dimension(1089, 631));
        setSize(new java.awt.Dimension(1089, 631));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCashier.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\Downloads\\CASHIER(2).png")); // NOI18N
        buttonCashier.setBorderPainted(false);
        buttonCashier.setFocusPainted(false);
        buttonCashier.setFocusable(false);
        buttonCashier.setRequestFocusEnabled(false);
        buttonCashier.setRolloverEnabled(false);
        buttonCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCashierActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 137, -1, 288));

        buttonManager1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/profile/manager.png"))); // NOI18N
        buttonManager1.setBorderPainted(false);
        buttonManager1.setFocusPainted(false);
        buttonManager1.setFocusable(false);
        buttonManager1.setRequestFocusEnabled(false);
        buttonManager1.setRolloverEnabled(false);
        buttonManager1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManager1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonManager1, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 137, -1, 288));

        buttonCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/profile/customer.png"))); // NOI18N
        buttonCustomer.setBorderPainted(false);
        buttonCustomer.setFocusPainted(false);
        buttonCustomer.setFocusable(false);
        buttonCustomer.setRequestFocusEnabled(false);
        buttonCustomer.setRolloverEnabled(false);
        buttonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 137, -1, 288));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/background/finalff.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCashierActionPerformed
        new CashierView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonCashierActionPerformed

    private void buttonManager1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManager1ActionPerformed
        
    }//GEN-LAST:event_buttonManager1ActionPerformed

    private void buttonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomerActionPerformed
        new OrderingView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCashier;
    private javax.swing.JButton buttonCustomer;
    private javax.swing.JButton buttonManager1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
