
package fastfood.system;

import java.awt.Color;
import javax.swing.JButton;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class OrderingView extends javax.swing.JFrame {

    public OrderingView() {
        initComponents();
        // removes highlighting effect when pressed
        JButton[] buttons = {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton4,
        jButton10, jButton11, jButton12, jButton13};

        for (JButton button : buttons) {
            button.setContentAreaFilled(false);
        }
    }
    public class Products { // todo: constructors, this keyword, super method explain.
        String name;
        int quantity;
        int price;
        
        public Products(String name, int quantity, int price){
            this.name = name;
            this.quantity = quantity;
            this.price = price;
        }
    }
    public class SpecialBurgers extends Products { // parent class for special burgers  
        public SpecialBurgers(String name, int quantity, int price){
            super(name, quantity, price);
        }
    }
    public class SpBurger1 extends SpecialBurgers { // child class
        public SpBurger1(){ // constructor
             super("DBB", 0, 230);
        }
    }
    public class SpBurger2 extends SpecialBurgers {
        public SpBurger2(){
            super("DBB", 0, 240);
        }
    }
    public class SpBurger3 extends SpecialBurgers {
        public SpBurger3(){
            super("DBB", 0, 250);
        }
    }
    public class SpBurger4 extends SpecialBurgers {
        public SpBurger4(){
            super("DBB", 0, 260);
        }
    }
    public class SpBurger5 extends SpecialBurgers {
        public SpBurger5(){
            super("DBB", 0, 270);
        }
    }
    public class SpBurger6 extends SpecialBurgers {
        public SpBurger6(){
            super("DBB", 0, 280);
        }
    }
    // Initialize Objects for Button ActionListeners
    SpBurger1 sp1 = new SpBurger1();
    SpBurger2 sp2 = new SpBurger2();
    SpBurger3 sp3 = new SpBurger3();
    SpBurger4 sp4 = new SpBurger4();
    SpBurger5 sp5 = new SpBurger5();
    SpBurger6 sp6 = new SpBurger6();
    
    double productSubtotal=0f, productTax=0f, productDiscount=0f, productTotalPrice=0f;
    double taxPercentage=0.12f, discountPercentage=0f;
    
    //List for Special Burgers
    public void getItemsWithQuantity(){
        ArrayList<Products> items = new ArrayList<>(); // items is a list that can store anything that is a SpecialBurgers class and sp1, sp2, sp3, ... are subclasses of SpecialBurgers.

        if(sp1.quantity > 0) items.add(sp1); // if product has quantity > 0 or it's selected for order, then store it in the list.
        if(sp2.quantity > 0) items.add(sp2);
        if(sp3.quantity > 0) items.add(sp3);    
        if(sp4.quantity > 0) items.add(sp4);
        if(sp5.quantity > 0) items.add(sp5);
        if(sp6.quantity > 0) items.add(sp6);

//            for(int i=0; i<items.size(); i++){ // test
//                System.out.println(items.get(i));
//            }   

        // To-DO: Add list for every product category below;

        // Subtotal, Tax, Discount, Total Computation
        productSubtotal=productTax=productDiscount=productTotalPrice=0f;          
        //calculate subtotal
        for (Products item : items) {
            productSubtotal += item.price * item.quantity;
        }
        //calculate tax
        productTax = productSubtotal * taxPercentage;
        //calculate total
        productTotalPrice = productSubtotal + productTax;
        System.out.println(productSubtotal + " " + productTax + " " + productDiscount + " " + productTotalPrice);

        //Displaying orders (data) through JTable
        DefaultTableModel table = (DefaultTableModel)jTableMyOrder.getModel();
        table.setRowCount(0);   // refresh list every method call for updated list.        
        for (Products item : items) {
            table.addRow(new Object[]{item.quantity, item.name, item.price, (item.quantity*item.price)});
        }
        table.fireTableDataChanged();   
    }
          
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSpBurger = new javax.swing.JButton();
        btnChckBurger = new javax.swing.JButton();
        btnBurger = new javax.swing.JButton();
        btnMiniBurger = new javax.swing.JButton();
        btnHotdogs = new javax.swing.JButton();
        btnGrills = new javax.swing.JButton();
        btnDesserts = new javax.swing.JButton();
        btnSides = new javax.swing.JButton();
        btnDrinks = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        sidebar3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMyOrder = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnPayNow = new javax.swing.JButton();
        btnPayNow1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jtxtSubtotal = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jtxtTAX = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jtxtDiscount = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel68 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jtxtQty11 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel69 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jtxtQty12 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel71 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jtxtQty13 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel70 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jtxtQty14 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel72 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jtxtQty15 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel73 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jtxtQty16 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 239, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("ORDERING SYSTEM");
        sidebar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, 20));

        btnSpBurger.setBackground(new java.awt.Color(37, 150, 190));
        btnSpBurger.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSpBurger.setForeground(new java.awt.Color(0, 0, 0));
        btnSpBurger.setText("    Special Burgers");
        btnSpBurger.setBorder(null);
        btnSpBurger.setFocusPainted(false);
        btnSpBurger.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSpBurger.setInheritsPopupMenu(true);
        btnSpBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpBurgerActionPerformed(evt);
            }
        });
        sidebar.add(btnSpBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 102, 224, 36));

        btnChckBurger.setBackground(new java.awt.Color(255, 255, 255));
        btnChckBurger.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnChckBurger.setForeground(new java.awt.Color(0, 0, 0));
        btnChckBurger.setText("    Chicken Burgers");
        btnChckBurger.setBorder(null);
        btnChckBurger.setFocusPainted(false);
        btnChckBurger.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnChckBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChckBurgerActionPerformed(evt);
            }
        });
        sidebar.add(btnChckBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 144, 224, 36));

        btnBurger.setBackground(new java.awt.Color(255, 255, 255));
        btnBurger.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBurger.setForeground(new java.awt.Color(0, 0, 0));
        btnBurger.setText("    Burgers");
        btnBurger.setBorder(null);
        btnBurger.setFocusPainted(false);
        btnBurger.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBurgerActionPerformed(evt);
            }
        });
        sidebar.add(btnBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 186, 224, 36));

        btnMiniBurger.setBackground(new java.awt.Color(255, 255, 255));
        btnMiniBurger.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMiniBurger.setForeground(new java.awt.Color(0, 0, 0));
        btnMiniBurger.setText("    Mini Burgers");
        btnMiniBurger.setBorder(null);
        btnMiniBurger.setFocusPainted(false);
        btnMiniBurger.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMiniBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiniBurgerActionPerformed(evt);
            }
        });
        sidebar.add(btnMiniBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 228, 224, 36));

        btnHotdogs.setBackground(new java.awt.Color(255, 255, 255));
        btnHotdogs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHotdogs.setForeground(new java.awt.Color(0, 0, 0));
        btnHotdogs.setText("    Hotdogs");
        btnHotdogs.setBorder(null);
        btnHotdogs.setFocusPainted(false);
        btnHotdogs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHotdogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotdogsActionPerformed(evt);
            }
        });
        sidebar.add(btnHotdogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 224, 36));

        btnGrills.setBackground(new java.awt.Color(255, 255, 255));
        btnGrills.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGrills.setForeground(new java.awt.Color(0, 0, 0));
        btnGrills.setText("    Grills");
        btnGrills.setBorder(null);
        btnGrills.setFocusPainted(false);
        btnGrills.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGrills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrillsActionPerformed(evt);
            }
        });
        sidebar.add(btnGrills, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 312, 224, 36));

        btnDesserts.setBackground(new java.awt.Color(255, 255, 255));
        btnDesserts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDesserts.setForeground(new java.awt.Color(0, 0, 0));
        btnDesserts.setText("    Desserts");
        btnDesserts.setBorder(null);
        btnDesserts.setFocusPainted(false);
        btnDesserts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDesserts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDessertsActionPerformed(evt);
            }
        });
        sidebar.add(btnDesserts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 354, 224, 36));

        btnSides.setBackground(new java.awt.Color(255, 255, 255));
        btnSides.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSides.setForeground(new java.awt.Color(0, 0, 0));
        btnSides.setText("    Sides");
        btnSides.setBorder(null);
        btnSides.setFocusPainted(false);
        btnSides.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSides.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSidesActionPerformed(evt);
            }
        });
        sidebar.add(btnSides, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 396, 224, 36));

        btnDrinks.setBackground(new java.awt.Color(255, 255, 255));
        btnDrinks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDrinks.setForeground(new java.awt.Color(0, 0, 0));
        btnDrinks.setText("    Drinks");
        btnDrinks.setBorder(null);
        btnDrinks.setFocusPainted(false);
        btnDrinks.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinksActionPerformed(evt);
            }
        });
        sidebar.add(btnDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 438, 224, 36));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\OneDrive\\Desktop\\fastfoodsystem\\fastfood-system\\icons\\Webalys-Kameleon.pics-Food-Dome.48.png")); // NOI18N
        sidebar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 50, 60));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("MENU");
        sidebar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 20));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("FASTFOOD");
        sidebar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        jPanel1.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        sidebar3.setBackground(new java.awt.Color(255, 255, 255));
        sidebar3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("MY ORDER");
        sidebar3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 107, 36));

        jTableMyOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Qty", "Product", "Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableMyOrder.setEnabled(false);
        jTableMyOrder.setFocusable(false);
        jTableMyOrder.setShowGrid(false);
        jTableMyOrder.getTableHeader().setResizingAllowed(false);
        jTableMyOrder.getTableHeader().setReorderingAllowed(false);
        jTableMyOrder.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTableMyOrderInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMyOrder);
        if (jTableMyOrder.getColumnModel().getColumnCount() > 0) {
            jTableMyOrder.getColumnModel().getColumn(0).setResizable(false);
            jTableMyOrder.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableMyOrder.getColumnModel().getColumn(1).setMinWidth(60);
            jTableMyOrder.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTableMyOrder.getColumnModel().getColumn(1).setMaxWidth(60);
            jTableMyOrder.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        sidebar3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 48, 200, 290));

        btnPayNow.setBackground(new java.awt.Color(255, 102, 102));
        btnPayNow.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnPayNow.setForeground(new java.awt.Color(255, 255, 255));
        btnPayNow.setText("ORDER LIST");
        btnPayNow.setBorderPainted(false);
        btnPayNow.setFocusPainted(false);
        btnPayNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayNowActionPerformed(evt);
            }
        });

        btnPayNow1.setBackground(new java.awt.Color(0, 204, 51));
        btnPayNow1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnPayNow1.setForeground(new java.awt.Color(0, 0, 0));
        btnPayNow1.setText("PAY NOW");
        btnPayNow1.setBorderPainted(false);
        btnPayNow1.setFocusPainted(false);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Subtotal:");

        jtxtSubtotal.setEditable(false);
        jtxtSubtotal.setBackground(new java.awt.Color(255, 255, 255));
        jtxtSubtotal.setForeground(java.awt.Color.black);
        jtxtSubtotal.setText("Php ");
        jtxtSubtotal.setToolTipText("");
        jtxtSubtotal.setBorder(null);
        jtxtSubtotal.setOpaque(true);
        jtxtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubtotalActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("TAX:");

        jtxtTAX.setEditable(false);
        jtxtTAX.setBackground(new java.awt.Color(255, 255, 255));
        jtxtTAX.setForeground(new java.awt.Color(0, 0, 0));
        jtxtTAX.setText("Php ");
        jtxtTAX.setBorder(null);
        jtxtTAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTAXActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Discount:");

        jtxtDiscount.setEditable(false);
        jtxtDiscount.setBackground(new java.awt.Color(255, 255, 255));
        jtxtDiscount.setForeground(new java.awt.Color(0, 0, 0));
        jtxtDiscount.setText("Php ");
        jtxtDiscount.setBorder(null);
        jtxtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDiscountActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Total:");

        jtxtTotal.setEditable(false);
        jtxtTotal.setBackground(new java.awt.Color(255, 255, 255));
        jtxtTotal.setForeground(new java.awt.Color(0, 0, 0));
        jtxtTotal.setText("Php ");
        jtxtTotal.setBorder(null);
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPayNow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPayNow1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTAX, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPayNow, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jtxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jtxtTAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jtxtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnPayNow1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        sidebar3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 345, -1, 200));

        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 552, 200, 80));

        jPanel1.add(sidebar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, -1, 630));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel68.setBackground(java.awt.Color.white);
        jPanel68.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Double Beef Burger (300g)");
        jPanel68.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, 201, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Php 230.00");
        jPanel68.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 151, 201, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\OneDrive\\Desktop\\fastfoodsystem\\fastfood-system\\icons\\Paomedia-Small-N-Flat-Sign-add.24.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel68.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 177, 35, 33));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\Downloads\\Gakuseisean-Ivista-Minus.24.png")); // NOI18N
        jButton2.setBorder(null);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel68.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 177, 35, 33));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField1.setText("Quantity:");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel68.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 177, 53, 33));

        jtxtQty11.setEditable(false);
        jtxtQty11.setBackground(new java.awt.Color(255, 255, 255));
        jtxtQty11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtxtQty11.setForeground(new java.awt.Color(51, 153, 0));
        jtxtQty11.setText("0");
        jtxtQty11.setBorder(null);
        jtxtQty11.setFocusable(false);
        jtxtQty11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQty11ActionPerformed(evt);
            }
        });
        jPanel68.add(jtxtQty11, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 177, 44, 33));
        jPanel68.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 201, 125));
        jPanel68.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, 189, 125));

        jPanel69.setBackground(java.awt.Color.white);
        jPanel69.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Double Beef Burger (300g)");
        jPanel69.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, 203, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Php 999.99");
        jPanel69.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 151, 203, -1));

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\OneDrive\\Desktop\\fastfoodsystem\\fastfood-system\\icons\\Paomedia-Small-N-Flat-Sign-add.24.png")); // NOI18N
        jButton3.setBorder(null);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel69.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 177, 35, 33));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\Downloads\\Gakuseisean-Ivista-Minus.24.png")); // NOI18N
        jButton4.setBorder(null);
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel69.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 177, 35, 33));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField3.setText("Quantity:");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel69.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 177, 53, 33));

        jtxtQty12.setEditable(false);
        jtxtQty12.setBackground(new java.awt.Color(255, 255, 255));
        jtxtQty12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtxtQty12.setForeground(new java.awt.Color(51, 153, 0));
        jtxtQty12.setText("0");
        jtxtQty12.setBorder(null);
        jtxtQty12.setFocusable(false);
        jPanel69.add(jtxtQty12, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 177, 44, 33));
        jPanel69.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 0, -1, 125));

        jPanel71.setBackground(java.awt.Color.white);
        jPanel71.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Double Beef Burger (300g)");
        jPanel71.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, 201, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Php 999.99");
        jPanel71.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 151, 201, -1));

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\OneDrive\\Desktop\\fastfoodsystem\\fastfood-system\\icons\\Paomedia-Small-N-Flat-Sign-add.24.png")); // NOI18N
        jButton7.setBorder(null);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel71.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 177, 35, 33));

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\Downloads\\Gakuseisean-Ivista-Minus.24.png")); // NOI18N
        jButton8.setBorder(null);
        jButton8.setFocusPainted(false);
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel71.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 177, 35, 33));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField7.setText("Quantity:");
        jTextField7.setBorder(null);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel71.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 177, 53, 33));

        jtxtQty13.setEditable(false);
        jtxtQty13.setBackground(new java.awt.Color(255, 255, 255));
        jtxtQty13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtxtQty13.setForeground(new java.awt.Color(51, 153, 0));
        jtxtQty13.setText("0");
        jtxtQty13.setBorder(null);
        jtxtQty13.setFocusable(false);
        jtxtQty13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQty13ActionPerformed(evt);
            }
        });
        jPanel71.add(jtxtQty13, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 177, 44, 33));
        jPanel71.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 201, 125));

        jPanel70.setBackground(java.awt.Color.white);
        jPanel70.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Double Beef Burger (300g)");
        jPanel70.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, 201, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Php 999.99");
        jPanel70.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 151, 201, -1));

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\OneDrive\\Desktop\\fastfoodsystem\\fastfood-system\\icons\\Paomedia-Small-N-Flat-Sign-add.24.png")); // NOI18N
        jButton5.setBorder(null);
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel70.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 177, 35, 33));

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\Downloads\\Gakuseisean-Ivista-Minus.24.png")); // NOI18N
        jButton6.setBorder(null);
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel70.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 177, 35, 33));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField5.setText("Quantity:");
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel70.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 177, 53, 33));

        jtxtQty14.setEditable(false);
        jtxtQty14.setBackground(new java.awt.Color(255, 255, 255));
        jtxtQty14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtxtQty14.setForeground(new java.awt.Color(51, 153, 0));
        jtxtQty14.setText("0");
        jtxtQty14.setBorder(null);
        jtxtQty14.setFocusable(false);
        jPanel70.add(jtxtQty14, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 177, 44, 33));
        jPanel70.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 201, 125));

        jPanel72.setBackground(java.awt.Color.white);
        jPanel72.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Double Beef Burger (300g)");
        jPanel72.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, 201, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Php 999.99");
        jPanel72.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 151, 201, -1));

        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\OneDrive\\Desktop\\fastfoodsystem\\fastfood-system\\icons\\Paomedia-Small-N-Flat-Sign-add.24.png")); // NOI18N
        jButton10.setBorder(null);
        jButton10.setFocusPainted(false);
        jButton10.setFocusable(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel72.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 177, 35, 33));

        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\Downloads\\Gakuseisean-Ivista-Minus.24.png")); // NOI18N
        jButton11.setBorder(null);
        jButton11.setFocusPainted(false);
        jButton11.setFocusable(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel72.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 177, 35, 33));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField9.setText("Quantity:");
        jTextField9.setBorder(null);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel72.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 177, 53, 33));

        jtxtQty15.setEditable(false);
        jtxtQty15.setBackground(new java.awt.Color(255, 255, 255));
        jtxtQty15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtxtQty15.setForeground(new java.awt.Color(51, 153, 0));
        jtxtQty15.setText("0");
        jtxtQty15.setBorder(null);
        jtxtQty15.setFocusable(false);
        jtxtQty15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQty15ActionPerformed(evt);
            }
        });
        jPanel72.add(jtxtQty15, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 177, 44, 33));
        jPanel72.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 201, 125));

        jPanel73.setBackground(java.awt.Color.white);
        jPanel73.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Double Beef Burger (300g)");
        jPanel73.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, 201, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Php 999.99");
        jPanel73.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 151, 201, -1));

        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\OneDrive\\Desktop\\fastfoodsystem\\fastfood-system\\icons\\Paomedia-Small-N-Flat-Sign-add.24.png")); // NOI18N
        jButton12.setBorder(null);
        jButton12.setFocusPainted(false);
        jButton12.setFocusable(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel73.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 177, 35, 33));

        jButton13.setIcon(new javax.swing.ImageIcon("C:\\Users\\markj\\Downloads\\Gakuseisean-Ivista-Minus.24.png")); // NOI18N
        jButton13.setBorder(null);
        jButton13.setFocusPainted(false);
        jButton13.setFocusable(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel73.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 177, 35, 33));

        jTextField11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField11.setText("Quantity:");
        jTextField11.setBorder(null);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel73.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 177, 53, 33));

        jtxtQty16.setEditable(false);
        jtxtQty16.setBackground(new java.awt.Color(255, 255, 255));
        jtxtQty16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtxtQty16.setForeground(new java.awt.Color(51, 153, 0));
        jtxtQty16.setText("0");
        jtxtQty16.setBorder(null);
        jtxtQty16.setFocusable(false);
        jPanel73.add(jtxtQty16, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 177, 44, 33));
        jPanel73.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 201, 125));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jPanel68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel69, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jPanel70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel3);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel9);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel6);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel10);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanel14);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", jPanel15);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab7", jPanel16);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab8", jPanel17);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab9", jPanel19);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 640, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChckBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChckBurgerActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        //reset color to white
        //to-do: DRY principle dito
        btnSpBurger.setBackground(Color.white);
        btnHotdogs.setBackground(Color.white);
        btnGrills.setBackground(Color.white);
        btnDesserts.setBackground(Color.white);
        btnSides.setBackground(Color.white);
        btnDrinks.setBackground(Color.white);
        btnBurger.setBackground(Color.white);
        btnMiniBurger.setBackground(Color.white);
        //selected button is highlighted
        btnChckBurger.setBackground(new java.awt.Color(37, 150, 190)); 
                
    }//GEN-LAST:event_btnChckBurgerActionPerformed

    private void btnSpBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpBurgerActionPerformed
        jTabbedPane1.setSelectedIndex(0);
            
        //reset color to white
        btnChckBurger.setBackground(Color.white);
        btnHotdogs.setBackground(Color.white);
        btnGrills.setBackground(Color.white);
        btnDesserts.setBackground(Color.white);
        btnSides.setBackground(Color.white);
        btnDrinks.setBackground(Color.white);
        btnBurger.setBackground(Color.white);
        btnMiniBurger.setBackground(Color.white);
        //selected button is highlighted
        btnSpBurger.setBackground(new java.awt.Color(37, 150, 190)); 
    }//GEN-LAST:event_btnSpBurgerActionPerformed

    private void btnBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurgerActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        
        //reset color to white
        btnChckBurger.setBackground(Color.white);
        btnHotdogs.setBackground(Color.white);
        btnGrills.setBackground(Color.white);
        btnDesserts.setBackground(Color.white);
        btnSides.setBackground(Color.white);
        btnDrinks.setBackground(Color.white);
        btnSpBurger.setBackground(Color.white);
        btnMiniBurger.setBackground(Color.white);
        //selected button is highlighted
        btnBurger.setBackground(new java.awt.Color(37, 150, 190)); 
    }//GEN-LAST:event_btnBurgerActionPerformed

    private void btnMiniBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiniBurgerActionPerformed
        jTabbedPane1.setSelectedIndex(3);
        
        //reset color to white
        btnChckBurger.setBackground(Color.white);
        btnHotdogs.setBackground(Color.white);
        btnGrills.setBackground(Color.white);
        btnDesserts.setBackground(Color.white);
        btnSides.setBackground(Color.white);
        btnDrinks.setBackground(Color.white);
        btnBurger.setBackground(Color.white);
        btnSpBurger.setBackground(Color.white);
        //selected button is highlighted
        btnMiniBurger.setBackground(new java.awt.Color(37, 150, 190)); 
    }//GEN-LAST:event_btnMiniBurgerActionPerformed

    private void btnHotdogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotdogsActionPerformed
        jTabbedPane1.setSelectedIndex(4);
        
        //reset color to white
        btnChckBurger.setBackground(Color.white);
        btnSpBurger.setBackground(Color.white);
        btnGrills.setBackground(Color.white);
        btnDesserts.setBackground(Color.white);
        btnSides.setBackground(Color.white);
        btnDrinks.setBackground(Color.white);
        btnBurger.setBackground(Color.white);
        btnMiniBurger.setBackground(Color.white);
        //selected button is highlighted
        btnHotdogs.setBackground(new java.awt.Color(37, 150, 190)); 
    }//GEN-LAST:event_btnHotdogsActionPerformed

    private void btnGrillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrillsActionPerformed
        jTabbedPane1.setSelectedIndex(5);
        
        //reset color to white
        btnChckBurger.setBackground(Color.white);
        btnHotdogs.setBackground(Color.white);
        btnSpBurger.setBackground(Color.white);
        btnDesserts.setBackground(Color.white);
        btnSides.setBackground(Color.white);
        btnDrinks.setBackground(Color.white);
        btnBurger.setBackground(Color.white);
        btnMiniBurger.setBackground(Color.white);
        //selected button is highlighted
        btnGrills.setBackground(new java.awt.Color(37, 150, 190)); 
    }//GEN-LAST:event_btnGrillsActionPerformed

    private void btnDessertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDessertsActionPerformed
        jTabbedPane1.setSelectedIndex(6);
        
        //reset color to white
        btnChckBurger.setBackground(Color.white);
        btnHotdogs.setBackground(Color.white);
        btnGrills.setBackground(Color.white);
        btnSpBurger.setBackground(Color.white);
        btnSides.setBackground(Color.white);
        btnDrinks.setBackground(Color.white);
        btnBurger.setBackground(Color.white);
        btnMiniBurger.setBackground(Color.white);
        //selected button is highlighted
        btnDesserts.setBackground(new java.awt.Color(37, 150, 190)); 
    }//GEN-LAST:event_btnDessertsActionPerformed

    private void btnSidesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSidesActionPerformed
        jTabbedPane1.setSelectedIndex(7);
        
        //reset color to white
        btnChckBurger.setBackground(Color.white);
        btnHotdogs.setBackground(Color.white);
        btnGrills.setBackground(Color.white);
        btnDesserts.setBackground(Color.white);
        btnSpBurger.setBackground(Color.white);
        btnDrinks.setBackground(Color.white);
        btnBurger.setBackground(Color.white);
        btnMiniBurger.setBackground(Color.white);
        //selected button is highlighted
        btnSides.setBackground(new java.awt.Color(37, 150, 190)); 
    }//GEN-LAST:event_btnSidesActionPerformed

    private void btnDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinksActionPerformed
        jTabbedPane1.setSelectedIndex(8);
        
        //reset color to white
        btnChckBurger.setBackground(Color.white);
        btnHotdogs.setBackground(Color.white);
        btnGrills.setBackground(Color.white);
        btnDesserts.setBackground(Color.white);
        btnSides.setBackground(Color.white);
        btnSpBurger.setBackground(Color.white);
        btnBurger.setBackground(Color.white);
        btnMiniBurger.setBackground(Color.white);
        //selected button is highlighted
        btnDrinks.setBackground(new java.awt.Color(37, 150, 190)); 
    }//GEN-LAST:event_btnDrinksActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jtxtQty15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQty15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtQty15ActionPerformed

    private void jtxtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubtotalActionPerformed

    }//GEN-LAST:event_jtxtSubtotalActionPerformed

    private void jtxtTAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTAXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTAXActionPerformed

    private void jtxtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDiscountActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(sp1.quantity >= 0){
            sp1.quantity++;
            String value = Integer.toString(sp1.quantity);
            jtxtQty11.setText(value);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtQty11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQty11ActionPerformed
        
    }//GEN-LAST:event_jtxtQty11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(sp1.quantity > 0){
            sp1.quantity--;
            String value = Integer.toString(sp1.quantity);
            jtxtQty11.setText(value);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTableMyOrderInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTableMyOrderInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableMyOrderInputMethodTextChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(sp2.quantity >= 0){
            sp2.quantity++;
            String value = Integer.toString(sp2.quantity);
            jtxtQty12.setText(value);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtxtQty13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQty13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtQty13ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(sp2.quantity > 0){
            sp2.quantity--;
            String value = Integer.toString(sp2.quantity);
            jtxtQty12.setText(value);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(sp3.quantity >= 0){
            sp3.quantity++;
            String value = Integer.toString(sp3.quantity);
            jtxtQty13.setText(value);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(sp3.quantity > 0){
            sp3.quantity--;
            String value = Integer.toString(sp3.quantity);
            jtxtQty13.setText(value);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(sp4.quantity >= 0){
            sp4.quantity++;
            String value = Integer.toString(sp4.quantity);
            jtxtQty14.setText(value);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(sp4.quantity > 0){
            sp4.quantity--;
            String value = Integer.toString(sp4.quantity);
            jtxtQty14.setText(value);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(sp5.quantity >= 0){
            sp5.quantity++;
            String value = Integer.toString(sp5.quantity);
            jtxtQty15.setText(value);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(sp5.quantity > 0){
            sp5.quantity--;
            String value = Integer.toString(sp5.quantity);
            jtxtQty15.setText(value);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if(sp6.quantity >= 0){
            sp6.quantity++;
            String value = Integer.toString(sp6.quantity);
            jtxtQty16.setText(value);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if(sp6.quantity > 0){
            sp6.quantity--;
            String value = Integer.toString(sp6.quantity);
            jtxtQty16.setText(value);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void btnPayNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayNowActionPerformed
          // method call
          getItemsWithQuantity(); 
          
          //updates product total cost
          jtxtSubtotal.setText(String.format("Php %.2f", productSubtotal));
          jtxtTAX.setText(String.format("Php %.2f", productTax));
          jtxtDiscount.setText(String.format("Php %.2f", productDiscount));
          jtxtTotal.setText(String.format("Php %.2f", productTotalPrice));
 
          jtxtSubtotal.revalidate();
          jtxtSubtotal.repaint();

    }//GEN-LAST:event_btnPayNowActionPerformed

    public static void main(String args[]) {

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderingView().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBurger;
    private javax.swing.JButton btnChckBurger;
    private javax.swing.JButton btnDesserts;
    private javax.swing.JButton btnDrinks;
    private javax.swing.JButton btnGrills;
    private javax.swing.JButton btnHotdogs;
    private javax.swing.JButton btnMiniBurger;
    private javax.swing.JButton btnPayNow;
    private javax.swing.JButton btnPayNow1;
    private javax.swing.JButton btnSides;
    private javax.swing.JButton btnSpBurger;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableMyOrder;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jtxtDiscount;
    private javax.swing.JTextField jtxtQty11;
    private javax.swing.JTextField jtxtQty12;
    private javax.swing.JTextField jtxtQty13;
    private javax.swing.JTextField jtxtQty14;
    private javax.swing.JTextField jtxtQty15;
    private javax.swing.JTextField jtxtQty16;
    private javax.swing.JTextField jtxtSubtotal;
    private javax.swing.JTextField jtxtTAX;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel sidebar3;
    // End of variables declaration//GEN-END:variables
}
